In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

csv_file_path = '/content/drive/MyDrive/LoL_champion_dataset/champions.csv'


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv(csv_file_path)

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df.head()


ID     Name                Title  \
0   Aatrox   Aatrox     the Darkin Blade   
1     Ahri     Ahri  the Nine-Tailed Fox   
2    Akali    Akali   the Rogue Assassin   
3   Akshan   Akshan   the Rogue Sentinel   
4  Alistar  Alistar         the Minotaur   

                                                                                                                                                                                                                                                             Blurb  \
0  Once honored defenders of Shurima against the Void, Aatrox and his brethren would eventually become an even greater threat to Runeterra, and were defeated only by cunning mortal sorcery. But after centuries of imprisonment, Aatrox was the first to find...   
1       Innately connected to the magic of the spirit realm, Ahri is a fox-like vastaya who can manipulate her prey's emotions and consume their essence—receiving flashes of their memory and insight from each soul she consumes. Once a powerful yet wayward...   
2    Abandoning the Kinkou Order and her title of the Fist of Shadow, Akali now strikes alone, ready to be the deadly weapon her people need. Though she holds onto all she learned from her master Shen, she has pledged to defend Ionia from its enemies, one...   
3    Raising an eyebrow in the face of danger, Akshan fights evil with dashing charisma, righteous vengeance, and a conspicuous lack of shirts. He is highly skilled in the art of stealth combat, able to evade the eyes of his enemies and reappear when they...   
4      Always a mighty warrior with a fearsome reputation, Alistar seeks revenge for the death of his clan at the hands of the Noxian empire. Though he was enslaved and forced into the life of a gladiator, his unbreakable will was what kept him from truly...   

      Partype  Attack  Defense  Magic  Difficulty   HP  HP_per_Level   MP  MP_per_Level  \
0  Blood Well       8        4      3           4  650           114    0           0.0   
1        Mana       3        4      8           5  590           104  418          25.0   
2      Energy       5        3      8           7  600           119  200           0.0   
3        Mana       0        0      0           0  630           107  350          40.0   
4        Mana       6        9      5           7  685           120  350          40.0   

   Move_Speed  Armor  Armor_per_Level  Spell_Block  Spell_Block_per_Level  Attack_Range  HP_Regen  \
0         345     38              4.8           32                   2.05           175      3.00   
1         330     21              4.7           30                   1.30           550      2.50   
2         345     23              4.7           37                   2.05           125      9.00   
3         330     26              4.7           30                   1.30           500      3.75   
4         330     47              4.7           32                   2.05           125      8.50   

   HP_Regen_per_Level  MP_Regen  MP_Regen_per_Level  Crit  Crit_per_Level  Attack_Damage  \
0                0.50       0.0                 0.0     0               0             60   
1                0.60       8.0                 0.8     0               0             53   
2                0.90      50.0                 0.0     0               0             62   
3                0.65       8.2                 0.7     0               0             52   
4                0.85       8.5                 0.8     0               0             62   

   Attack_Damage_per_Level  Attack_Speed_per_Level  Attack_Speed      Tags  
0                     5.00                   2.500         0.651   Fighter  
1                     3.00                   2.200         0.668      Mage  
2                     3.30                   3.200         0.625  Assassin  
3                     3.00                   4.000         0.638  Marksman  
4                     3.75                   2.125         0.625      Tank

In [ ]:
df.nunique()

ID                         170
Name                       170
Title                      170
Blurb                      170
Partype                     12
Attack                      11
Defense                     11
Magic                       11
Difficulty                  11
HP                          54
HP_per_Level                35
MP                          69
MP_per_Level                32
Move_Speed                   9
Armor                       25
Armor_per_Level             20
Spell_Block                 10
Spell_Block_per_Level       10
Attack_Range                19
HP_Regen                    19
HP_Regen_per_Level          14
MP_Regen                    37
MP_Regen_per_Level          14
Crit                         1
Crit_per_Level               1
Attack_Damage               25
Attack_Damage_per_Level     37
Attack_Speed_per_Level      56
Attack_Speed                33
Tags                         6
dtype: int64

In [ ]:
df.drop(columns=['ID', 'Title', 'Blurb', 'Crit', 'Crit_per_Level'], inplace=True)
df.head()

Name     Partype  Attack  Defense  Magic  Difficulty   HP  HP_per_Level   MP  MP_per_Level  \
0   Aatrox  Blood Well       8        4      3           4  650           114    0           0.0   
1     Ahri        Mana       3        4      8           5  590           104  418          25.0   
2    Akali      Energy       5        3      8           7  600           119  200           0.0   
3   Akshan        Mana       0        0      0           0  630           107  350          40.0   
4  Alistar        Mana       6        9      5           7  685           120  350          40.0   

   Move_Speed  Armor  Armor_per_Level  Spell_Block  Spell_Block_per_Level  Attack_Range  HP_Regen  \
0         345     38              4.8           32                   2.05           175      3.00   
1         330     21              4.7           30                   1.30           550      2.50   
2         345     23              4.7           37                   2.05           125      9.00   
3         330     26              4.7           30                   1.30           500      3.75   
4         330     47              4.7           32                   2.05           125      8.50   

   HP_Regen_per_Level  MP_Regen  MP_Regen_per_Level  Attack_Damage  Attack_Damage_per_Level  \
0                0.50       0.0                 0.0             60                     5.00   
1                0.60       8.0                 0.8             53                     3.00   
2                0.90      50.0                 0.0             62                     3.30   
3                0.65       8.2                 0.7             52                     3.00   
4                0.85       8.5                 0.8             62                     3.75   

   Attack_Speed_per_Level  Attack_Speed      Tags  
0                   2.500         0.651   Fighter  
1                   2.200         0.668      Mage  
2                   3.200         0.625  Assassin  
3                   4.000         0.638  Marksman  
4                   2.125         0.625      Tank

In [ ]:
df['Partype'].unique()

array(['Blood Well', 'Mana', 'Energy', nan, 'Fury', 'Rage', 'Courage',
       'Shield', 'Ferocity', 'Heat', 'Grit', 'Crimson Rush', 'Flow'],
      dtype=object)

In [ ]:
df['Partype'] = df['Partype'].apply(lambda x: x if x in ['Mana', 'Energy'] else 'None')
df['Partype'].unique()

array(['None', 'Mana', 'Energy'], dtype=object)

In [ ]:
df['Partype'] = df['Partype'].map({'Mana':2,'Energy':1,'None':0})
df['Tags'] = df['Tags'].map({'Fighter':5,'Mage':4,'Assassin':3,'Marksman':2,'Tank':1,'Support':0})

In [ ]:
# Exclude the 'Name' column and scale the remaining columns
scaler = MinMaxScaler()
# Exclude the 'Tags' column and scale the remaining columns
df_scaled = df.drop(['Name', 'Tags'], axis=1)
# Apply MinMaxScaler
df_scaled = pd.DataFrame(scaler.fit_transform(df_scaled), columns=df_scaled.columns)
# Reattach the 'Name' column
df_scaled['Name'] = df['Name']
df_scaled['Tags'] = df['Tags']

In [ ]:
df_scaled.head()

Partype  Attack  Defense  Magic  Difficulty        HP  HP_per_Level      MP  MP_per_Level  \
0      0.0     0.8      0.4    0.3         0.4  0.839161      0.789474  0.0000      0.000000   
1      1.0     0.3      0.4    0.8         0.5  0.629371      0.614035  0.0418      0.287356   
2      0.5     0.5      0.3    0.8         0.7  0.664336      0.877193  0.0200      0.000000   
3      1.0     0.0      0.0    0.0         0.0  0.769231      0.666667  0.0350      0.459770   
4      1.0     0.6      0.9    0.5         0.7  0.961538      0.894737  0.0350      0.459770   

   Move_Speed     Armor  Armor_per_Level  Spell_Block  Spell_Block_per_Level  Attack_Range  \
0       0.750  0.689655         0.872727     0.666667               0.655172      0.095238   
1       0.375  0.103448         0.854545     0.533333               0.137931      0.809524   
2       0.750  0.172414         0.854545     1.000000               0.655172      0.000000   
3       0.375  0.275862         0.854545     0.533333               0.137931      0.714286   
4       0.375  1.000000         0.854545     0.666667               0.655172      0.000000   

   HP_Regen  HP_Regen_per_Level  MP_Regen  MP_Regen_per_Level  Attack_Damage  \
0     0.300                0.40     0.000                 0.0           0.64   
1     0.250                0.48     0.160                 0.8           0.36   
2     0.900                0.72     1.000                 0.0           0.72   
3     0.375                0.52     0.164                 0.7           0.32   
4     0.850                0.68     0.170                 0.8           0.72   

   Attack_Damage_per_Level  Attack_Speed_per_Level  Attack_Speed     Name  Tags  
0                     1.00                0.416667      0.469333   Aatrox     5  
1                     0.60                0.366667      0.514667     Ahri     4  
2                     0.66                0.533333      0.400000    Akali     3  
3                     0.60                0.666667      0.434667   Akshan     2  
4                     0.75                0.354167      0.400000  Alistar     1

In [ ]:
# Assuming df contains the features (X) and target labels (y)
X = df_scaled.drop(['Name', 'Tags'], axis=1)  # Drop 'Name' and 'tags' column
y = df_scaled['Tags']  # Target labels

# Split the data into training and test sets (80% for training, 20% for testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize KNN and SVM models
knn = KNeighborsClassifier(n_neighbors=5)
svm = SVC(kernel='linear', C=1,probability=True, random_state=42)  # Use probability=True for soft voting

# Initialize the VotingClassifier with hard voting (default)
ensemble_model = VotingClassifier(estimators=[('knn', knn), ('svm', svm)], voting='hard')



In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Function to print model metrics
def print_model_metrics(model, X_train, y_train, model_name="Model"):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_train)

    accuracy = accuracy_score(y_train, y_pred)
    precision = precision_score(y_train, y_pred, average='weighted')
    recall = recall_score(y_train, y_pred, average='weighted')
    f1 = f1_score(y_train, y_pred, average='weighted')
    conf_matrix = confusion_matrix(y_train, y_pred)

    print(f"Confusion Matrix:\n{conf_matrix}")
    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1-Score: {f1}\n")


In [ ]:
print(f"Training Data Metrics KNN:\n")
print_model_metrics(knn, X_train, y_train, model_name="KNN")

Training Data Metrics KNN:

Confusion Matrix:
[[ 9  1  1  0  1  1]
 [ 1 13  0  1  0  3]
 [ 1  0 22  0  0  1]
 [ 0  0  0  3  2  7]
 [ 2  0  2  1 28  0]
 [ 0  2  0  2  1 31]]
Accuracy: 0.7794117647058824
Precision: 0.7699731287863982
Recall: 0.7794117647058824
F1-Score: 0.7705083364886617



In [ ]:
print(f"Testing Data Metrics KNN:\n")
print_model_metrics(knn, X_test, y_test, model_name="KNN")

Testing Data Metrics KNN:

Confusion Matrix:
[[ 3  1  0  0  0  0]
 [ 0  4  0  0  0  2]
 [ 0  0  4  0  0  0]
 [ 0  0  1  3  0  1]
 [ 0  0  1  0  3  0]
 [ 0  0  0  0  0 11]]
Accuracy: 0.8235294117647058
Precision: 0.8561624649859945
Recall: 0.8235294117647058
F1-Score: 0.8191405653170358



--------------------------------------------------------------------------------

In [ ]:
print(f"Training Data Metrics SVM:\n")
print_model_metrics(svm, X_train, y_train, model_name="SVM")

Training Data Metrics SVM:

Confusion Matrix:
[[ 9  0  0  0  2  2]
 [ 0 16  0  0  0  2]
 [ 0  0 22  0  1  1]
 [ 0  0  0  3  2  7]
 [ 0  1  0  0 32  0]
 [ 0  2  0  0  1 33]]
Accuracy: 0.8455882352941176
Precision: 0.8702012383900929
Recall: 0.8455882352941176
F1-Score: 0.8311784202179



In [ ]:
print(f"Testing Data Metrics SVM:\n")
print_model_metrics(svm, X_test, y_test, model_name="SVM")

Testing Data Metrics SVM:

Confusion Matrix:
[[ 3  1  0  0  0  0]
 [ 0  5  0  0  0  1]
 [ 0  0  4  0  0  0]
 [ 0  0  1  3  0  1]
 [ 0  0  0  0  4  0]
 [ 0  0  0  0  0 11]]
Accuracy: 0.8823529411764706
Precision: 0.8972850678733032
Recall: 0.8823529411764706
F1-Score: 0.876984126984127



--------------------------------------------------------------------------------

In [ ]:
print(f"Training Data Metrics Ensemble:\n")
print_model_metrics(ensemble_model, X_train, y_train, model_name="Ensemble")

Training Data Metrics Ensemble:

Confusion Matrix:
[[10  1  0  0  1  1]
 [ 1 15  0  0  0  2]
 [ 1  0 23  0  0  0]
 [ 0  0  0  4  2  6]
 [ 2  1  2  0 28  0]
 [ 0  3  0  2  1 30]]
Accuracy: 0.8088235294117647
Precision: 0.8046545733678087
Recall: 0.8088235294117647
F1-Score: 0.8009916967236738



In [ ]:
print(f"Testing Data Metrics Ensemble:\n")
print_model_metrics(ensemble_model, X_test, y_test, model_name="Ensemble")

Testing Data Metrics Ensemble:

Confusion Matrix:
[[ 3  1  0  0  0  0]
 [ 0  5  0  0  0  1]
 [ 0  0  4  0  0  0]
 [ 0  0  1  4  0  0]
 [ 0  0  1  0  3  0]
 [ 0  0  0  0  0 11]]
Accuracy: 0.8823529411764706
Precision: 0.9044117647058822
Recall: 0.8823529411764706
F1-Score: 0.883039012706532



In [ ]:
import pandas as pd

# Map for category labels
category_map = {
    'Fighter': 5,
    'Mage': 4,
    'Assassin': 3,
    'Marksman': 2,
    'Tank': 1,
    'Support': 0
}

# Prepare a list to store results
results = []

# Loop through the test set
for i in range(len(X_test)):
    # Get the true label for the current sample
    true_label = y_test.iloc[i]
    true_label_name = list(category_map.keys())[list(category_map.values()).index(true_label)]

    # Get the corresponding features from X_test
    sample_features = X_test.iloc[i].to_frame().T  # Convert to DataFrame with original feature names

    # Get the 'Name' of the sample from the original dataset (df)
    sample_name = df.loc[X_test.index[i], 'Name']

    # Predict the label using the ensemble model
    predicted_label = ensemble_model.predict(sample_features)
    predicted_label_name = list(category_map.keys())[list(category_map.values()).index(predicted_label[0])]

    # Determine if the prediction is correct
    correct_prediction = (true_label == predicted_label[0])

    # Append the result to the list
    results.append([sample_name, true_label_name, predicted_label_name, correct_prediction])

# Convert the results list to a DataFrame
results_df = pd.DataFrame(results, columns=['Name', 'True Label', 'Predicted Label', 'Correct Prediction'])

# Print the results as a table
print(results_df)


           Name True Label Predicted Label  Correct Prediction
0       Trundle    Fighter         Fighter                True
1         Elise   Assassin        Marksman               False
2         Shaco   Assassin        Assassin                True
3          Ekko   Assassin        Assassin                True
4         Urgot    Fighter         Fighter                True
5           Zac       Tank         Fighter               False
6         Ziggs       Mage            Mage                True
7           Jax    Fighter         Fighter                True
8        Rammus       Tank            Tank                True
9      Katarina   Assassin        Assassin                True
10      Belveth    Fighter         Fighter                True
11      XinZhao    Fighter         Fighter                True
12        Taric    Support            Tank               False
13         Hwei       Mage        Marksman               False
14       KSante       Tank            Tank             